// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk264pGCDVR_RjG7iN78D5BnMcn00fD6s',
    appId: '1:253626105127:web:137b45d1b871d0437b3d02',
    messagingSenderId: '253626105127',
    projectId: 'famsync-ccc45',
    authDomain: 'famsync-ccc45.firebaseapp.com',
    storageBucket: 'famsync-ccc45.firebasestorage.app',
    measurementId: 'G-6BM7VN7TPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl__ZcxVcf6PoQ4wy9PmWS--cRZ67wxaA',
    appId: '1:253626105127:android:9ff7fd71859a7cd17b3d02',
    messagingSenderId: '253626105127',
    projectId: 'famsync-ccc45',
    storageBucket: 'famsync-ccc45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1e4jdNqI_s8HL_u5sWqPtFXwL2p9Xt0E',
    appId: '1:253626105127:ios:2a75105e357441387b3d02',
    messagingSenderId: '253626105127',
    projectId: 'famsync-ccc45',
    storageBucket: 'famsync-ccc45.firebasestorage.app',
    iosBundleId: 'com.jelujr.famsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1e4jdNqI_s8HL_u5sWqPtFXwL2p9Xt0E',
    appId: '1:253626105127:ios:ece3199bf5d593e27b3d02',
    messagingSenderId: '253626105127',
    projectId: 'famsync-ccc45',
    storageBucket: 'famsync-ccc45.firebasestorage.app',
    iosBundleId: 'com.example.smartFamily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk264pGCDVR_RjG7iN78D5BnMcn00fD6s',
    appId: '1:253626105127:web:61a200e23773f5a87b3d02',
    messagingSenderId: '253626105127',
    projectId: 'famsync-ccc45',
    authDomain: 'famsync-ccc45.firebaseapp.com',
    storageBucket: 'famsync-ccc45.firebasestorage.app',
    measurementId: 'G-KS6GTHXCTP',
  );
}
