// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTr7fIv8RG56fPqOuTZY2wUejSkbjxWA4',
    appId: '1:465560650321:web:5a7b8247eae7497e97ae70',
    messagingSenderId: '465560650321',
    projectId: 'famsync-17',
    authDomain: 'famsync-17.firebaseapp.com',
    storageBucket: 'famsync-17.firebasestorage.app',
    measurementId: 'G-KW1J59JG57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgp135owJIqNzzifqNWMmbBqDM68JUH5M',
    appId: '1:465560650321:android:c18f10a7cd0757a797ae70',
    messagingSenderId: '465560650321',
    projectId: 'famsync-17',
    storageBucket: 'famsync-17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ_xyrPquyPFNM588KxChC5PAtgP9_6Cw',
    appId: '1:465560650321:ios:4040ed155b9c21b397ae70',
    messagingSenderId: '465560650321',
    projectId: 'famsync-17',
    storageBucket: 'famsync-17.firebasestorage.app',
    iosBundleId: 'com.example.smartFamily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ_xyrPquyPFNM588KxChC5PAtgP9_6Cw',
    appId: '1:465560650321:ios:4040ed155b9c21b397ae70',
    messagingSenderId: '465560650321',
    projectId: 'famsync-17',
    storageBucket: 'famsync-17.firebasestorage.app',
    iosBundleId: 'com.example.smartFamily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTr7fIv8RG56fPqOuTZY2wUejSkbjxWA4',
    appId: '1:465560650321:web:30ac9caa9ef53d1d97ae70',
    messagingSenderId: '465560650321',
    projectId: 'famsync-17',
    authDomain: 'famsync-17.firebaseapp.com',
    storageBucket: 'famsync-17.firebasestorage.app',
    measurementId: 'G-78D1E816P7',
  );

}